modLoader = "javafml"
license = "LGPL v2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Dark-Utilities/issues"

[[mods]]
modId = "darkutils"
version = "26.2.0.0"
displayName = "DarkUtilities"
updateJSONURL = "https://updates.blamejared.com/get?n=darkutils&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dark-utilities"
logoFile = "logo_darkutils.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "A bit of everything."

[[mixins]]
config = "darkutils.common.mixins.json"

[[mixins]]
config = "darkutils.neoforge.mixins.json"

[[dependencies.darkutils]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkutils]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.8-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.darkutils]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

